feat: made an increment on slidedeck
mftenergy/Gitting-comfortable pull request #1
Opened 2024-08-28 12:50 UTC by EmilMunksoe

2024-08-30 05:29 UTC, rne-mft requested changes
I think it looks fine. Is it possible to see the slides already from the PR version before it gets merged? If so, that would be nice, it's easier for me to grasp the flow if I can run through them.

2024-08-30 05:29 UTC, rne-mft commented on slidedeck/slides.md
> +git push -u origin <branch> # Push all missing commits from localhost to a git server syncing your records with a server for collaboration
```suggestion
git push -u origin <branch> # Push all missing commits from localhost (your machine) to a git server syncing your records with a server for collaboration
```

2024-08-30 05:29 UTC, rne-mft commented on slidedeck/slides.md
> +Git works by a client (a user) downloads the source code from a `repository`, makes edit locally and syncs these edits to `origin` (the server of which you downloaded the source code). <br><br>
```suggestion
Git works by a client (a user) cloning the source code from a `repository`, performing edits locally and pushing these edits to `origin` (the server from which you downloaded the source code). <br><br>
```

2024-08-30 05:29 UTC, rne-mft commented on slidedeck/slides.md
> +# What is Slidev? asdasd test
```suggestion
```

2024-08-30 05:29 UTC, rne-mft commented on slidedeck/slides.md
>  Slidev is a slides maker and presenter designed for developers, consist of the following features
```suggestion
```

2024-09-02 07:42 UTC, EmilMunksoe commented on slidedeck/slides.md
> +# What is Slidev? asdasd test
Keep for now to make inspiration when you develop slides

2024-09-02 07:44 UTC, EmilMunksoe commented
@rne-mft See the README.md in the directory slidedeck. There are instructions on how to spin up the slidedeck locally.

2024-09-06 11:46 UTC, rne-mft approved these changes

2024-09-06 12:02 UTC, merged